# Generated by Django 2.1.3 on 2018-11-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.IntegerField(choices=[(0, 'new'), (1, 'registered'), (2, 'added_to_sending_queue'), (3, 'notify_sent')], default=0, verbose_name='Статус'),
        ),
    ]
