# Generated by Django 2.1 on 2018-12-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='number',
            field=models.SmallIntegerField(default=0, verbose_name='Порядок вывода на сайт'),
        ),
    ]
