# Generated by Django 2.1 on 2018-12-01 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_contact_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='sender_email',
            new_name='email',
        ),
    ]
