# Generated by Django 2.0.2 on 2018-11-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20181113_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='publish_on_main_page',
            field=models.BooleanField(default=False, verbose_name='Опубиковать на главной'),
        ),
    ]
