# Generated by Django 2.0.2 on 2018-11-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_document_publish_on_main_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(default='Без тэга', to='mainapp.Tag', verbose_name='Тэги'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(default='Без тэга', to='mainapp.Tag', verbose_name='Тэги'),
        ),
    ]
