# Generated by Django 2.0.2 on 2018-11-16 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20181113_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='short_description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_on_main_page',
            field=models.BooleanField(default=False, verbose_name='Опубликовать на главной'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'jpg', 'jpeg'], message='Неправильный тип файла, используйте PDF, DOCX, DOC, JPG, JPEG')], verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_on_main_page',
            field=models.BooleanField(default=False, verbose_name='Опубликовать на главной'),
        ),
    ]
