# Generated by Django 2.1 on 2018-12-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_staff_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='priority',
            field=models.SmallIntegerField(default=0, verbose_name='Приоритет'),
        ),
    ]
