# Generated by Django 2.1 on 2018-12-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20181202_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фотография'),
        ),
    ]
