# Generated by Django 2.0.2 on 2018-11-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20181116_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, verbose_name='Заголовок')),
                ('typeof', models.CharField(blank=True, max_length=64, verbose_name='Тип сообщения')),
                ('params', models.CharField(blank=True, max_length=512, verbose_name='Параметры сообщения')),
                ('sender_email', models.EmailField(blank=True, max_length=64, verbose_name='Адрес электронной почты')),
                ('sender_phone', models.CharField(blank=True, max_length=64, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
