# Generated by Django 2.0.2 on 2018-11-22 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата получения'),
        ),
    ]
