# Generated by Django 2.1 on 2018-12-02 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_staff_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, verbose_name='Название')),
                ('typeof', models.CharField(blank=True, max_length=64, verbose_name='Тип')),
                ('params', models.CharField(blank=True, max_length=999, verbose_name='Параметры')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата получения')),
                ('status', models.IntegerField(choices=[(0, 'new'), (1, 'published')], default=0, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Запись реестра',
                'verbose_name_plural': 'Записи реестра',
            },
        ),
    ]
