# Generated by Django 2.1.2 on 2018-12-04 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_registry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата получения'),
        ),
    ]
