# Generated by Django 2.1.2 on 2018-12-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20181204_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='created_date',
            field=models.DateField(blank=True, verbose_name='Дата получения'),
        ),
    ]
