# Generated by Django 2.1.2 on 2018-12-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20181204_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='registry',
            name='org',
            field=models.CharField(blank=True, max_length=120, verbose_name='Организация'),
        ),
    ]
